fileapp/urls.py
from django.conf.urls import url
from . import views

app_name = "fileapp"

urlpatterns = [
    url(r'^$', views.BasicUploadView.as_view(), name='index'),
    url(r'^clear/$', views.clear_database, name='clear_database'),
]

multiplefileupload/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("fileapp.urls")),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fileapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
import os


def document_directory_path(instance, filename):
    basename = os.path.basename(filename)
    name, ext = os.path.splitext(basename)
    file_type = ""
    image_list = ['.jpeg', '.jpg', '.gif', '.bmp', '.svg', '.psd', 'cpt',
                  'psp', 'cxf', 'pdn', 'jfif', 'exif', 'tiff', 'ppm', 'pgm ', 'pnm']
    video_list = ['.mp4', '.avi', '.wmv', '.m4a', '.3gp', '.3gpp', '.wav',
                  'mov', 'webm', 'hdv', 'vob', 'm4v', 'f4v', 'm4b', 'oga', 'ogv']
    if ext.lower() in image_list:
        file_type = "images"
    elif ext.lower() in video_list:
        file_type = "videos"
    else:
        file_type = "others"
    path = 'media/uploads/%Y/%m/%d/{}/{}{}'.format(file_type, name, ext)
    return datetime.now().strftime(path)


class Fileup(models.Model):
    file = models.FileField(upload_to=document_directory_path)

    def filename(self):
        return os.path.basename(self.file.name)

fileapp/forms.py
from django import forms
from .models import Fileup


class FileupForm(forms.ModelForm):
    class Meta:
        model = Fileup
        fields = ('file', )
        widgets = { 
            'file': forms.FileInput(attrs={'multiple': ''}),
        }  

fileapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views import View

from .forms import FileupForm
from .models import Fileup


class BasicUploadView(View):
    def get(self, request):
        file_list = Fileup.objects.all()
        return render(self.request, 'fileapp/index.html', {'files': file_list})

    def post(self, request):
        form = FileupForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            files = form.save()
            data = {'is_valid': True, 'name': files.file.name,
                    'url': files.file.url}
        else:
            data = {'is_valid': False}
        return JsonResponse(data)


def clear_database(request):
    for files in Fileup.objects.all():
        files.file.delete()
        files.delete()
    return redirect(request.POST.get('next'))

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>File upload</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-default custom_navbar">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand navbar_title" href="">Multiple Fileupload</a>
        </div>
        <div class="collapse navbar-collapse" id="main-menu">
          <ul class="nav navbar-nav">
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </body>
  <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous">
  </script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
</html>

templates/fileapp/index.html
{% extends 'base.html' %}
{% block content %}
<button type="button"  class="btn btn-default js-upload-photos">
  <span class="glyphicon glyphicon-cloud-upload "></span> Upload files
</button>
<form method="post" action="{% url 'fileapp:clear_database' %}">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ request.path }}">
  <button type="submit" style="margin-bottom: 15px; margin-top: -35px;" class="btn btn-danger pull-right">
    <span class="glyphicon glyphicon-trash"></span> Clear Database
  </button>
</form>
<input id="fileupload" type="file" name="file" multiple
       accept="image/*,video/*"
       style="display: none;"
       data-url="{% url 'fileapp:index' %}"
       data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
<table id="gallery" class="table table-bordered">
  <thead>
    <tr>
        <th>Files</th>
    </tr>
  </thead>
  <tbody>
     {% for file in files %}
      <tr>
        <td><a href="{{ file.file.url }}">{{ file.file.name }}</a></td>
      </tr>
     {% endfor %}
  </tbody>
</table>
<div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Uploading...</h4>
      </div>
      <div class="modal-body">
        <div class="progress">
          <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}